### PR TITLE
fix: fixed vesting periods being stored twice

### LINKED ISSUE #247: Duplicate vesting period entry
## Bug description
`vesting_period` should have unique `period_order`. currently all `vesting_periods` are duplicated

Screenshot 2021-10-25 at 10 37 44 PM

## Steps to reproduce
here is the query
```
query VestingAccount {
  vesting_account(where: {address: {_eq: "desmos14t2hvslx84klhdljkltlmeyz9fj6xfs3z40ne2"}}) {
    vesting_periods(order_by: {period_order: asc}) {
      amount
      period_order
      length
    }
    start_time
  }
}
```

### PR DESCRIPTION
**Pull request by rmontagnin**
## Description
This PR fixed the vesting periods being stored twice. It also introduced a new command to fix already stored periods: 
```
bdjuno fix auth vesting-accounts
```

Closes: #247

---

### Author Checklist

*All items are required. Please add a note to the item if the item is not applicable and
please add links to any relevant follow up issues.*

I have...

- [x] included the correct [type prefix](https://github.com/commitizen/conventional-commit-types/blob/v3.0.0/index.json) in the PR title
- [ ] added `!` to the type prefix if API or client breaking change
- [x] targeted the correct branch
- [x] provided a link to the relevant issue or specification
- [ ] added a changelog entry to `CHANGELOG.md`
- [ ] included comments for [documenting Go code](https://blog.golang.org/godoc)
- [ ] updated the relevant documentation or specification
- [x] reviewed "Files changed" and left comments if necessary
- [ ] confirmed all CI checks have passed

### Reviewers Checklist

*All items are required. Please add a note if the item is not applicable and please add
your handle next to the items reviewed if you only reviewed selected items.*

I have...

- [ ] confirmed the correct [type prefix](https://github.com/commitizen/conventional-commit-types/blob/v3.0.0/index.json) in the PR title
- [ ] confirmed `!` in the type prefix if API or client breaking change
- [ ] confirmed all author checklist items have been addressed
- [ ] reviewed API design and naming
- [ ] reviewed documentation is accurate
- [ ] reviewed tests and test coverage
- [ ] manually tested (if applicable)

### CODE REVIEW

File: database/auth.go [hunk 1]
```diff
@@ -115,7 +116,15 @@ func (db *Db) storeVestingAccount(account exported.VestingAccount) (int, error)
 
 // storeVestingPeriods handles storing the vesting periods of PeriodicVestingAccount type
 func (db *Db) storeVestingPeriods(id int, vestingPeriods []vestingtypes.Period) error {
-	stmt := `
+	// Delete already existing periods
+	stmt := `DELETE FROM vesting_period WHERE vesting_account_id = $1`
```
Comment (rmontagnin) [inline database/auth.go:120]: Since vesting periods do not have a unique id inside themselves, we need to delete all the periods of an account before storing them again. This way even if we parse the genesis multiple times we do not end up with an account that has duplicated periods

Comment (MonikaCat) [reply database/auth.go:120]: It works, however when I clear the data from vesting_account and vesting_period tables and run ```bdjuno fix auth vesting-accounts``` the id is incremented from the last stored id instead of starting from index 1


Screenshot 2021-10-26 at 4 19 36 PM

Comment (rmontagnin) [reply database/auth.go:120]: @MonikaCat That `id` is something that is only used internally from PostgreSQL. It' an auto-increment id that does not mean anything. It is normal to have it continuously increase rather than starting from `0` each time

**Review by huichiaotsou — APPROVED** [review]

File: database/auth.go (hunk 1 above)
Comment (MonikaCat) [reply database/auth.go:120]: Okay thanks for explaining :D

**Comment by MonikaCat** [comment]
LGTM, tested ACK

**Review by MonikaCat — APPROVED** [review]
