### PR TITLE
fix: validators voting power not updated when status changes

### LINKED ISSUE #270: Validator VP not updating when status changes
Reference: https://explorer.desmos.network/validators/desmosvaloper1t4urajq9xw4fppld2dl3xzwxqjkmjx9zfv3q5u
When a validator's status goes to unbonding or unbonded we should update the VP to 0. Currently it stays at the last block they signed i believe

### PR DESCRIPTION
**Pull request by rmontagnin**
## Description
This PR fixes the unbonding/unbonded validators voting power not updated correctly (closes #270)

---

### Author Checklist

*All items are required. Please add a note to the item if the item is not applicable and
please add links to any relevant follow up issues.*

I have...

- [x] included the correct [type prefix](https://github.com/commitizen/conventional-commit-types/blob/v3.0.0/index.json) in the PR title
- [ ] added `!` to the type prefix if API or client breaking change
- [x] targeted the correct branch
- [x] provided a link to the relevant issue or specification
- [ ] added a changelog entry to `CHANGELOG.md`
- [x] included comments for [documenting Go code](https://blog.golang.org/godoc)
- [ ] updated the relevant documentation or specification
- [x] reviewed "Files changed" and left comments if necessary
- [x] confirmed all CI checks have passed

### Reviewers Checklist

*All items are required. Please add a note if the item is not applicable and please add
your handle next to the items reviewed if you only reviewed selected items.*

I have...

- [ ] confirmed the correct [type prefix](https://github.com/commitizen/conventional-commit-types/blob/v3.0.0/index.json) in the PR title
- [ ] confirmed `!` in the type prefix if API or client breaking change
- [ ] confirmed all author checklist items have been addressed
- [ ] reviewed API design and naming
- [ ] reviewed documentation is accurate
- [ ] reviewed tests and test coverage
- [ ] manually tested (if applicable)

### CODE REVIEW

File: modules/staking/handle_block.go [hunk 1]
```diff
@@ -71,9 +71,16 @@ func (m *Module) updateValidatorVotingPower(height int64, vals *tmctypes.ResultV
...
+	votingPowers, err := m.GetValidatorsVotingPowers(height, vals)
+	if err != nil {
+		log.Error().Str("module", "staking").Err(err).Int64("height", height).
+			Msg("error while getting validators voting powers")
+		return
+	}
 
-	err := m.db.SaveValidatorsVotingPowers(votingPowers)
+	// Add all the voting powers of
+	err = m.db.SaveValidatorsVotingPowers(votingPowers)
```
Comment (huichiaotsou) [inline modules/staking/handle_block.go]: incomplete comment

File: modules/staking/handle_block.go [hunk 2]
```diff
@@ -71,9 +71,16 @@ func (m *Module) updateValidatorVotingPower(height int64, vals *tmctypes.ResultV
...
+	// Get the voting powers
+	votingPowers, err := m.GetValidatorsVotingPowers(height, vals)
+	if err != nil {
+		log.Error().Str("module", "staking").Err(err).Int64("height", height).
+			Msg("error while getting validators voting powers")
+		return
+	}
 
-	err := m.db.SaveValidatorsVotingPowers(votingPowers)
+	// Add all the voting powers of
```
Comment (rmontagnin) [inline modules/staking/handle_block.go]:
```suggestion
	// Save all the voting powers
```

**Review by huichiaotsou — APPROVED** [review]

**Review by MonikaCat — APPROVED** [review]
LGTM, tested on local
